### ISSUE TITLE
ThemeRegistration type isn't compatible with VS Code theme schema

### ISSUE THREAD

**Issue by gdomingu** [antfu/shikiji#63]
Hi there, 

I noticed that the [ThemeRegistration](https://github.com/antfu/shikiji/blob/main/packages/shikiji-core/src/types.ts#L363-L407) type isn't compatible with the shape of the schema when one exports a current theme via VS Code. 

`$schema: 'vscode://schemas/color-theme',`

`ThemeRegistration` seems to expect attributes `name`, `bg`, `fg`, and `settings`. All which don't appear in the `vscode://schemas/color-theme` schema. Wondering if there is a different type I should use that corresponds better with the vs code schema? 

Everything works as expected when I pass in the theme JSON, but I would like to declare the correct type instead of just using `any` in typescript. 

Thank you.

**Comment by antfu** [comment]
Most of them are not required. TextMeta theme does not usually care about background and default foreground color; `settings` are for VS-Code-specific colors (the color of panels, borders etc); `name` and `displayName` are just metadata; When `bg` and `fg` are not provided, we will try to look from `settings`, otherwise will fallback to default value. The other types are there to be compatible with other integrations but are not used by Shikiji itself.

**Comment by gdomingu** [comment]
Here is an example of the type error. 
```
is missing the following properties from type 'ThemeRegistration': name, settings, fg, bgts(2739)
```

![Image of type error](https://github.com/antfu/shikiji/assets/4443635/4cd3c13c-ddaf-44a9-ac83-93ea248206bd)

If `name` and `displayName` are just metadata and `bg` and `fg` have fallbacks could we mark those attributes as optional in the shikiji type?

**Comment by antfu** [comment]
You should use `ThemeRegistrationRaw` for that

**Comment by gdomingu** [comment]
It doesn't look like `ThemeRegistrationRaw` has properties `type`, `schema`, or `colors`.

![Image of error for ThemeRegistrationRaw](https://github.com/antfu/shikiji/assets/4443635/ac2387d6-511a-4775-9953-4f8638d659df)
